<a href="https://colab.research.google.com/github/sumpumm/Feature-Engineering/blob/main/Handling%20Categorical%20Data/ordinalEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning from scratch/Feature Engineering-04/Handling Categorical Data/customer.csv')

In [4]:
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [5]:
df = df.iloc[:,2:]
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [7]:
from sklearn.model_selection import train_test_split

x_train ,x_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1), df['purchased'], test_size= 0.2, random_state=0)

In [8]:
x_train

,review,education
33,Good,PG
35,Poor,School
26,Poor,PG
34,Average,School
18,Good,School
7,Poor,School
14,Poor,PG
45,Poor,PG
48,Good,UG
29,Average,UG


In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School', 'UG', 'PG']])

In [31]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [32]:
x_train_trans = oe.transform(x_train)

In [12]:
x_train_trans

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [33]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
le = LabelEncoder()

In [36]:
le.fit(y_train)

LabelEncoder()

In [17]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [37]:
y_train_trans = le.transform(y_train)
y_train_trans

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

###final data

In [43]:
df2 = pd.read_csv('/content/drive/MyDrive/Machine Learning from scratch/Feature Engineering-04/Handling Categorical Data/customer.csv')
df2 = df2.iloc[:,2:]

In [44]:
oe2 = OrdinalEncoder(categories=[['Poor','Average','Good'],['School', 'UG', 'PG']])
le2 = LabelEncoder()

oe2.fit(df2.drop('purchased', axis=1))
x_final = oe.transform(df2.drop('purchased', axis=1))

le2.fit(df2['purchased'])
y_final =le.transform(df2['purchased'])

In [45]:
x_final

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [48]:
final_transformed = np.hstack((df.iloc[:,:2],x_final))

In [49]:
final_transformed

array([[30, 'Female', 1.0, 0.0],
       [68, 'Female', 0.0, 1.0],
       [70, 'Female', 2.0, 2.0],
       [72, 'Female', 2.0, 2.0],
       [16, 'Female', 1.0, 1.0],
       [31, 'Female', 1.0, 0.0],
       [18, 'Male', 2.0, 0.0],
       [60, 'Female', 0.0, 0.0],
       [65, 'Female', 1.0, 1.0],
       [74, 'Male', 2.0, 1.0],
       [98, 'Female', 2.0, 1.0],
       [74, 'Male', 2.0, 1.0],
       [51, 'Male', 0.0, 0.0],
       [57, 'Female', 1.0, 0.0],
       [15, 'Male', 0.0, 2.0],
       [75, 'Male', 0.0, 1.0],
       [59, 'Male', 0.0, 1.0],
       [22, 'Female', 0.0, 1.0],
       [19, 'Male', 2.0, 0.0],
       [97, 'Male', 0.0, 2.0],
       [57, 'Female', 1.0, 0.0],
       [32, 'Male', 1.0, 2.0],
       [18, 'Female', 0.0, 2.0],
       [96, 'Female', 2.0, 0.0],
       [16, 'Female', 1.0, 2.0],
       [57, 'Female', 2.0, 0.0],
       [53, 'Female', 0.0, 2.0],
       [69, 'Female', 0.0, 2.0],
       [48, 'Male', 0.0, 0.0],
       [83, 'Female', 1.0, 1.0],
       [73, 'Male', 1.0, 1.0],
 

In [50]:
final_df = pd.DataFrame(final_transformed)

In [51]:
final_df.head()

,0,1,2,3
0,30,Female,1.0,0.0
1,68,Female,0.0,1.0
2,70,Female,2.0,2.0
3,72,Female,2.0,2.0
4,16,Female,1.0,1.0


In [52]:
final_df.columns=['age','gender','review', 'education']
final_df.sample(5)

,age,gender,review,education
36,34,Female,2.0,1.0
19,97,Male,0.0,2.0
3,72,Female,2.0,2.0
47,38,Female,2.0,2.0
9,74,Male,2.0,1.0


In [54]:
final_df['review'].values

array([1.0, 0.0, 2.0, 2.0, 1.0, 1.0, 2.0, 0.0, 1.0, 2.0, 2.0, 2.0, 0.0,
       1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 1.0, 1.0, 0.0, 2.0, 1.0, 2.0,
       0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 2.0, 1.0, 0.0, 2.0, 1.0, 2.0,
       0.0, 2.0, 2.0, 2.0, 0.0, 1.0, 0.0, 0.0, 2.0, 2.0, 2.0],
      dtype=object)

In [55]:
final_df.head()

,age,gender,review,education
0,30,Female,1.0,0.0
1,68,Female,0.0,1.0
2,70,Female,2.0,2.0
3,72,Female,2.0,2.0
4,16,Female,1.0,1.0
